### ISSUE TITLE
Issue in release mode build 

### ISSUE THREAD

**Issue by gunjchhetri** [Parassharmaa/usage_stats#1]
HI,
I am getting below error when I tried to build my app in release mode-

e: C:\src\flutter_window\flutter\.pub-cache\hosted\pub.dartlang.org\usage_stats-0.1.0\android\src\main\kotlin\io\github\parassharmaa\usage_stats\UsageStats.kt: (9, 28): Unresolved reference: RequiresApi
e: C:\src\flutter_window\flutter\.pub-cache\hosted\pub.dartlang.org\usage_stats-0.1.0\android\src\main\kotlin\io\github\parassharmaa\usage_stats\UsageStats.kt: (55, 6): Unresolved reference: RequiresApi
e: C:\src\flutter_window\flutter\.pub-cache\hosted\pub.dartlang.org\usage_stats-0.1.0\android\src\main\kotlin\io\github\parassharmaa\usage_stats\UsageStatsPlugin.kt: (5, 28): Unresolved reference: NonNull
e: C:\src\flutter_window\flutter\.pub-cache\hosted\pub.dartlang.org\usage_stats-0.1.0\android\src\main\kotlin\io\github\parassharmaa\usage_stats\UsageStatsPlugin.kt: (22, 38): Unresolved reference: NonNull
e: C:\src\flutter_window\flutter\.pub-cache\hosted\pub.dartlang.org\usage_stats-0.1.0\android\src\main\kotlin\io\github\parassharmaa\usage_stats\UsageStatsPlugin.kt: (42, 32): Unresolved reference: NonNull
e: C:\src\flutter_window\flutter\.pub-cache\hosted\pub.dartlang.org\usage_stats-0.1.0\android\src\main\kotlin\io\github\parassharmaa\usage_stats\UsageStatsPlugin.kt: (42, 59): Unresolved reference: NonNull
e: C:\src\flutter_window\flutter\.pub-cache\hosted\pub.dartlang.org\usage_stats-0.1.0\android\src\main\kotlin\io\github\parassharmaa\usage_stats\UsageStatsPlugin.kt: (88, 40): Unresolved reference: NonNull
e: C:\src\flutter_window\flutter\.pub-cache\hosted\pub.dartlang.org\usage_stats-0.1.0\android\src\main\kotlin\io\github\parassharmaa\usage_stats\Utils.kt: (11, 17): Unresolved reference: core

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

The plugin usage_stats could not be built due to the issue above.

Could you please have a look?

**Comment by Parassharmaa** [comment]
What is your ```minSdkVersion``` in build.gradle? Make sure it is 22 or greater.
