### ISSUE TITLE
Add feature to query network stats

### ISSUE THREAD

**Issue by Parassharmaa** [Parassharmaa/usage_stats#4]
Todo:
- Implement flutter methods to query network stats
- Implement query summary and query history API for network stats.

Reference:
- https://developer.android.com/reference/android/app/usage/NetworkStatsManager

**Comment by JacobKant** [comment]
i can try to help with this

**Comment by JacobKant** [comment]
i try add this feature, maybe is not complete
I didn't find how to implement the history api in the context of applications, only globally, so I haven't done it yet

**Comment by Parassharmaa** [comment]
Thank you for giving it a try. I guess for making it specific to an app, once needs to get `uid` for the package initially.
